// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyejifrjdddotpvagdbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZWppZnJqZGRkb3RwdmFnZGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzc4OTUsImV4cCI6MjA2MTkxMzg5NX0.om7GpBdbxow5eg4NPNUDAHq47AkfuLggpRo-jvRm0Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);